### ISSUE TITLE
where to find the "IT.CEL.SETS.P2" data?

### ISSUE THREAD

**Issue by liamxg** [emilmalta/30daychartchallenge#1]
Dear @emilmalta,

where to find the "IT.CEL.SETS.P2" data?

**Comment by emilmalta** [comment]
It's a dataset from `WDI`; a World Development Indicators API package.

Make sure it's installed:
`if(!require("WDI", quietly = FALSE)) install.packages("WDI")`

Query the table like so:
`WDI::WDI(indicator = "IT.CEL.SETS.P2", start = 1960, end = 2019)`

**Comment by liamxg** [comment]
Dear @emilmalta,

Thanks.
